### ISSUE TITLE
Question: App setup on Yahoo's side

### ISSUE THREAD

**Issue by lsbyerley** [whatadewitt/fantasy-starter-express#1]
Hello! Looking to use this to build an NFL drafting tool. When setting this up, what do you typically set the Home Page URL and Callback Domain to in the app settings (https://developer.yahoo.com/apps/create/) ? Does localhost work?

Also is there a reason why Yahoo emails you everytime you login, is that something new with Oauth2 verification?

**Comment by whatadewitt** [comment]
APOLOGIES! I totally missed this coming in.

I've always had issues with Yahoo! Auth and localhost/ports, so I set up something in my host and have Yahoo! look for that.

I often use something like www.fantasy.dev for my development sites.

**Comment by lsbyerley** [comment]
No worries.. I ended up doing the exact same thing... i added www.draftapp.dev to point to 127.0.0.1 in my hosts file and it works fine. Thanks for this starter.. its great
